name: Rob Jenkins Photo
favicon: null
layout_spectrum: 0.97822
typography_spectrum: 0.26918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171516'
    - '#6e98b0'
    - '#b6d0dd'
    - '#b63844'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
