name: Rob Jenkins Photo
favicon: null
layout_spectrum: 0.22584910108707845
typography_spectrum: 0.9404648838099092
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
